TestDjango/TestDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_api.viewsLogin import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('api/', include('rest_api.urls')),
    path('login/', login, name='login'),
]

TestDjango/core/urls.py
from .views import home, form_crea_usuario, form_login, categoria, lista_categorias, form_mod_categoria, form_del_categoria, form_crea_categoria, lista_juegos, lista_pokemones, lista_juegos_por_encargo, form_mod_juego, form_del_juego, form_crea_juego, cerrar_sesion, perfil_usuario
from django.urls import path

urlpatterns = [
    path('',home,name="home"),
    path('form_crea_usuario',form_crea_usuario,name="form_crea_usuario"),
    path('form_login',form_login,name="form_login"),
    path('cerrar_sesion',cerrar_sesion,name="cerrar_sesion"),
    path('categoria/<id>/<nombre>',categoria,name="categoria"),
    path('lista_categorias',lista_categorias,name="lista_categorias"),
    path('form_crea_categoria',form_crea_categoria,name="form_crea_categoria"),
    path('form_mod_categoria/<id>',form_mod_categoria,name="form_mod_categoria"),
    path('form_del_categoria/<id>',form_del_categoria,name="form_del_categoria"), 
    path('lista_juegos',lista_juegos,name="lista_juegos"),
    path('lista_pokemones',lista_pokemones,name="lista_pokemones"),
    path('lista_juegos_por_encargo',lista_juegos_por_encargo,name="lista_juegos_por_encargo"),
    path('form_crea_juego',form_crea_juego,name="form_crea_juego"),
    path('form_mod_juego/<id>',form_mod_juego,name="form_mod_juego"),
    path('form_del_juego/<id>',form_del_juego,name="form_del_juego"), 
    path('perfil_usuario',perfil_usuario, name="perfil_usuario"),
    ]

TestDjango/core/models.py
from django.db import models

# Create your models here.

class Perfil(models.Model):
    id_perfil = models.CharField(max_length=20, primary_key=True, verbose_name='Código perfil')
    nombre_perfil = models.CharField(max_length=50, verbose_name='Nombre perfil')

    def __str__(self):
        return self.nombre_perfil
    
class Region(models.Model):
    id_region = models.CharField(max_length=20, primary_key=True, verbose_name='Código región')
    nombre_region = models.CharField(max_length=50, verbose_name='Nombre región')

    def __str__(self):
        return self.nombre_region
    
class Comuna(models.Model):
    id_comuna = models.CharField(max_length=20, primary_key=True, verbose_name='Código comuna')
    nombre_comuna = models.CharField(max_length=50, verbose_name='Nombre comuna')
    id_region = models.ForeignKey(Region, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_comuna

class Usuario(models.Model):
    usuario = models.CharField(max_length=20, primary_key=True, verbose_name='Nombre usuario')
    nombre = models.CharField(max_length=50, verbose_name='Nombre completo')
    correo = models.CharField(max_length=50,verbose_name='Correo electronico')
    password = models.CharField(max_length=20,verbose_name='Password')
    fecha_nac = models.DateField(verbose_name='Fecha de nacimiento')
    direccion = models.CharField(max_length=100,verbose_name='Dirección despacho')
    id_perfil = models.ForeignKey(Perfil, default="1", on_delete=models.CASCADE)
    id_region = models.ForeignKey(Region, null=True, on_delete=models.CASCADE)
    id_comuna = models.ForeignKey(Comuna, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario

    
class CategoriaJuego(models.Model):
    id_categoria = models.CharField(max_length=20, primary_key=True, verbose_name='Código categoría')
    nombre_categoria = models.CharField(max_length=50, verbose_name='Nombre categoría')

    def __str__(self):
        return self.nombre_categoria
    
class Juego(models.Model):
    id_juego = models.CharField(max_length=20, primary_key=True, verbose_name='Código')
    nombre_juego = models.CharField(max_length=50, verbose_name='Nombre')
    descripcion_juego = models.CharField(max_length=200, verbose_name='Descripción')
    url_img_juego = models.CharField(max_length=50, verbose_name='URL imagen')
    precio_juego = models.IntegerField(verbose_name="Precio")
    id_categoria = models.ForeignKey(CategoriaJuego, on_delete=models.CASCADE)
    imagen_juego = models.ImageField(upload_to='imagenes/', null=True, verbose_name='Imagen del juego')

    def __str__(self):
        return self.nombre_juego

TestDjango/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuario, CategoriaJuego, Juego

class DateInput(forms.DateInput):
    input_type = 'date'

class TextInput(forms.TextInput):
    input_type = 'text'

class UsuarioForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = ['usuario','nombre','correo','password','fecha_nac','direccion','id_region','id_comuna']
        usuario = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario'}))
        nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario'}))
        correo = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario'}))
        ##password = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario', 'type':'password'}))
        direccion = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario'}))
        ##id_perfil = forms.CharField(widget=forms.TextInput(attrs={'class':'campo_formulario', 'type':'hidden'}))

        widgets = {
            'fecha_nac': DateInput(attrs={'class':'campo_formulario'}),
            'password': TextInput(attrs={type:'password'}),
        }

class LoginForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = ['usuario','password']
        widgets = {
            'password': TextInput(attrs={'type':'password'}),
        }

class CategoriasForm(ModelForm):

    class Meta:
        model = CategoriaJuego
        fields = ['id_categoria','nombre_categoria']

class JuegoForm(ModelForm):

    class Meta:
        model = Juego
        fields = ['id_juego','nombre_juego','descripcion_juego','url_img_juego' ,'precio_juego','id_categoria']

TestDjango/core/views.py
from .forms import UsuarioForm, LoginForm, CategoriasForm, JuegoForm 
from .models import Usuario, CategoriaJuego, Juego, Perfil
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from html import unescape

import requests

# Create your views here.

def home(request):
    usuario_conectado = request.session.get('user', '')
    role = request.session.get('role', '1')

    categorias = CategoriaJuego.objects.all()
    datos = {
        'categorias':categorias,
        'usuario_conectado':usuario_conectado,
        'role':role
    }
    print("Rol en home " + role)
    return render(request, "core/home.html", datos)

def cerrar_sesion(request):
    request.session['user'] = ''
    request.session['role'] = '1'
    return render(request, "core/cerrar_sesion.html")

def categoria(request, id, nombre):
    print("id " + id)
    print("nombre " + nombre)
    juegos = Juego.objects.filter(id_categoria=id)
    datos = {
        'nombre':nombre,
        'juegos':juegos
    }

    return render(request, "core/categoria.html", datos)

def lista_categorias(request):

    categorias = CategoriaJuego.objects.all().order_by('id_categoria')
    print("cantidad de categorias")
    print(categorias.count())
    datos = {
        'categorias':categorias
    }
    return render(request, "core/lista_categorias.html", datos)


def form_mod_categoria(request, id):

    categoria = CategoriaJuego.objects.get(id_categoria=id)
    print("cantidad a modificar")
    print(id)
    datos = {
        'form':CategoriasForm(instance=categoria),
    }
    if request.method == 'POST':
        formulario = CategoriasForm(request.POST, request.FILES, instance=categoria)
        formulario.save()
        return redirect('/lista_categorias')
        
    return render(request, 'core/form_mod_categoria.html', datos)

def form_del_categoria(request, id):

    categoria = CategoriaJuego.objects.get(id_categoria=id)
    print("id a borrar")
    print(id)

    if request.method == 'POST':
        categoria.delete()
       
        return redirect('/lista_categorias')
    
    return render(request, 'core/form_del_categoria.html', {'categoria':categoria})

def form_crea_categoria(request):
    datos = {
        'form': CategoriasForm()
    }
    print("Entrando a vista crea categoria")
    if request.method == 'POST':
        formulario = CategoriasForm(request.POST, request.FILES)
        if formulario.is_valid(): 
            print("Formulario correcto")
            formulario.save()
            datos['mensaje'] = "Guardado correctamente"
            return redirect('/lista_categorias')
        else: 
            datos['mensaje'] = "Error " + formulario.errors.as_text()
        
    return render(request, 'core/form_crea_categoria.html', datos)

def form_crea_usuario(request):
    datos = {
        'form': UsuarioForm()
    }
    print("Entrando a vista crea usuario")
    if request.method == 'POST':
        formulario = UsuarioForm(request.POST, request.FILES)
        if formulario.is_valid(): 
            print("Formulario correcto")
            formulario.save()
            datos['mensaje'] = "Guardado correctamente"
        else: 
            datos['mensaje'] = "Error " + formulario.errors.as_text()
        
    return render(request, 'core/form_crea_usuario.html', datos)

def form_login(request):

    request.session['user'] = ''
    request.session['role'] = '1'

    datos = {
        'form': LoginForm(),
        'perfil':''
    }
    print("Entrando a vista login")
    if request.method == 'POST':
        formulario = LoginForm(request.POST, request.FILES)
        data = request.POST
        usuario_form = data.get('usuario')
        clave_form = data.get('password')
        
        print("usuario_form " + usuario_form)
        print("clave_form " + clave_form)
        
        try:
            user = Usuario.objects.get(usuario=usuario_form)
        

            clave = user.password
            role = user.id_perfil.id_perfil
            print("clave " + clave)



            print("Formulario correcto")
            if clave == clave_form:
                print("clave correcta " + clave)
                datos['mensaje'] = "Clave correcta"
                request.session['user'] = usuario_form
                request.session['role'] = role
                print("Role " + role)
                datos['role'] = role
            else:
                print("clave incorrecta" + clave)
                datos['mensaje'] = "Clave incorrecta"

        except ObjectDoesNotExist:
            datos['mensaje'] = "Usuario no existe, por favor regístrese"

        
    return render(request, 'core/form_login.html', datos)

def lista_juegos(request):

    juegos = Juego.objects.all().order_by('id_juego')
    print("cantidad de juegos")
    print(juegos.count())
    datos = {
        'juegos':juegos
    }
    return render(request, "core/lista_juegos.html", datos)


def form_mod_juego(request, id):

    juego = Juego.objects.get(id_juego=id)
    print("juego a modificar")
    print(id)
    datos = {
        'form':JuegoForm(instance=juego),
    }
    if request.method == 'POST':
        formulario = JuegoForm(request.POST, request.FILES, instance=juego)
        formulario.save()
        return redirect('/lista_juegos')
        
    return render(request, 'core/form_mod_juego.html', datos)

def form_del_juego(request, id):

    juego = Juego.objects.get(id_juego=id)
    print("id a borrar")
    print(id)

    if request.method == 'POST':
        juego.delete()
       
        return redirect('/lista_juegos')
    
    return render(request, 'core/form_del_juego.html', {'juego':juego})

def form_crea_juego(request):
    datos = {
        'form': JuegoForm()
    }
    print("Entrando a vista crea juego")
    if request.method == 'POST':
        formulario = JuegoForm(request.POST, request.FILES)
        if formulario.is_valid(): 
            print("Formulario correcto")
            formulario.save()
            datos['mensaje'] = "Guardado correctamente"
            return redirect('/lista_juegos')
        else: 
            datos['mensaje'] = "Error " + formulario.errors.as_text()
        
    return render(request, 'core/form_crea_juego.html', datos)

def perfil_usuario(request):
    usuario_conectado = request.session.get('user', '')

    return render(request, 'core/perfil_usuario.html', {'usuario_conectado': usuario_conectado})

    #url = "https://rickandmortyapi.com/api/character"

def lista_juegos_por_encargo(request):

    params = {
        'api_key': 'ebd57961cb2382983090d52649c7f7e3dc5c01a5',
        'format': 'json',
          }
    
    headers = {
    'User-Agent': 'j.gormaz@duocuc.cl'
    }

                             
    url = "https://www.giantbomb.com/api/games/"

    response = requests.get(url, params = params, headers=headers)
    print(response.status_code)
    #juegos = response.json().get("results",[])
    if response.status_code == 200:
        juegos = response.json().get("results",[])
        print("juegos")
        #print(juegos)
        for juego in juegos:
            if juego is not None and 'description' in juego and juego['description'] is not None:
                juego['description'] = unescape(juego['description'])
            else:
                juego['description'] = ''

    else: 
        juegos = []

    datos = {
        'juegos':juegos
    }
    return render(request, "core/lista_juegos_por_encargo.html", datos)


def lista_pokemones(request):
                         
    response = requests.get('https://pokeapi.co/api/v2/pokemon?limit=100')
    data = response.json()
    pokemons = data['results']

    for pokemon in pokemons:
        url = pokemon['url']
        response = requests.get(url)
        data = response.json()
        pokemon['image'] = data['sprites']['front_default']
    
    return render(request, "core/lista_pokemones.html", {"pokemons": pokemons})

TestDjango/core/templates/core/accion.html
<!DOCTYPE html>
<html>

    <head>
        {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>

        <div>
            <a id="inicio" href="/">>>>Inicio</a>
            <nav>
                <a id='inicio_sesion' href="form_crea_usuario">Registro usuario</a>
            </nav>
        </div>

        <header>
            <h1>ACCIÓN</h1>
        </header>
        {% load static%}
        <main>
            <ul class="listado-producto">
                <li>
                    <h2>GTA V</h2>
                    <img src="{% static 'core/img/ac_gtav.png' %}" alt="GTA V">
                    <p class="descripcion-producto">Se lo que quieras ser en la entrega más aclamada de GTA, para jugar local o de forma online</p>
                    <p class="precio-producto">$19.990</p>
                </li>
                <li>
                    <h2>Horizon Forbidden West</h2>
                    <img src="{% static 'core/img/ac_horizon.png' %}" alt="WoW">
                    <p class="descripcion-producto">Acompaña a Aloy en sus aventuras en este mundo inhóspito para conocer la verdad detrás de su nacimiento</p>
                    <p class="precio-producto">$29.990</p>
                </li>
            </ul>
        </main>

        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                    <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                    <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                    <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>

    </body>

TestDjango/core/templates/core/categoria.html
<!DOCTYPE html>
<html>

    <head>
        {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>

        <div>
            <a id="inicio" href="/">>Inicio</a>
            <nav>
                {% if role == '2' %}
                  <p id='inicio_sesion'>Su perfil es Administrador</a>
                {% endif %}
            </nav>
        </div>

        <header>
            <h1>{{nombre}}</h1>
        </header>
        {% load static%}
        <main>
            <div class="contenido">
                <ul class="listado-producto">
                    {% for juego in juegos %}
                    <li>
                        <h2>{{ juego.nombre_juego }}</h2>
                            <img src="{{juego.url_img_juego}}" alt="{{ juego.nombre_juego }}">
                        <p class="descripcion-producto">{{ juego.descripcion_juego }}</p>
                        <p class="precio-producto">
                            {% if juego.precio_juego == 0 %}
                                GRATIS </p>
                            {% else %}
                                ${{juego.precio_juego}}</p>
                            {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </main>

        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                    <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                    <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                    <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>

    </body>

TestDjango/core/templates/core/cerrar_sesion.html
<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


    <head>
      {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>          
        
      <div>
        <a id="inicio" href="/">>Inicio</a>
        <nav>
          {% if role == '2' %}
            <p id='inicio_sesion'>Su perfil es Administrador</a>
          {% endif %}
      </nav>
      </div>    

        <header>            
            <h1>
                SESIÓN CERRADA
            </h1>

        </header>

        <main>
            <br>


        </main>
    
        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                  <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                  <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                  <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>
    </body>


</html>

TestDjango/core/templates/core/form_crea_categoria.html
<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


    <head>
      {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>          
        
      <div>
        <a id="inicio" href="/">>Inicio</a>
        <nav>
          {% if role == '2' %}
            <p id='inicio_sesion'>Su perfil es Administrador</a>
          {% endif %}
        </nav>
      </div>    

        <header>            
            <h1>
                Nueva Categoría
            </h1>
        </header>

        <main>
            <br>

            <div class='formulario'>
              <br><br>
              <form method="post" id="formulario_nueva_categoria" onreset="location.reload()">
                  {% csrf_token %}
                  {% for field in form%}
                      <div id="campo_formulario">
                      <label for="{{field.id_for_label}}">
                          {{field.label}}
                      </label><br>
                      {{field}}
                      </div>
                  {% endfor %}
                  <div id="campo_formulario">
                    <input type="submit" value="Enviar">
                    <input type="reset" value="Limpiar">
                  </div>
              </form>
            </div>
            <div class="alert alert-success" role="alert">
              {{ mensaje }}
            </div>
        </main>
    
        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                  <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                  <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                  <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>
        {% load static%}
        <script src="{% static 'core/js/validaciones.js' %}"></script>
    </body>


</html>

TestDjango/core/templates/core/form_crea_juego.html
<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


    <head>
      {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>          
        
      <div>
        <a id="inicio" href="/">>Inicio</a>
        <nav>
          {% if role == '2' %}
            <p id='inicio_sesion'>Su perfil es Administrador</a>
          {% endif %}
        </nav>
      </div>    

        <header>            
            <h1>
                Nuevo Juego
            </h1>

        </header>

        <main>
            <br>

            <div class='formulario'>
              <br><br>
              <form method="post" id="formulario_nuevo_juego" onreset="location.reload()">
                  {% csrf_token %}
                  {% for field in form%}
                      <div id="campo_formulario">
                      <label for="{{field.id_for_label}}">
                          {{field.label}}
                      </label><br>
                      {{field}}
                      </div>
                  {% endfor %}
                  <div id="campo_formulario">
                    <input type="submit" value="Enviar">
                    <input type="reset" value="Limpiar">
                  </div>
              </form>
            </div>
            <div class="alert alert-success" role="alert">
              {{ mensaje }}
            </div>
        </main>
    
        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                  <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                  <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                  <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>
        {% load static%}
        <script src="{% static 'core/js/validaciones.js' %}"></script>
    </body>


</html>

TestDjango/core/templates/core/form_crea_usuario.html
<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


    <head>
      {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>          
        
      <div>
        <a id="inicio" href="/">>>>Inicio</a>
        <nav>
          {% if role == '2' %}
            <p id='inicio_sesion'>Su perfil es Administrador</a>
          {% endif %}
      </nav>
      </div>    

        <header>            
            <h1>
                REGISTRO USUARIO
            </h1>

        </header>

        <main>
            <br>

            <div class='formulario'>
              <br><br>
              <form method="post" id="formulario_registro" onreset="location.reload()">
                  {% csrf_token %}
                  {% for field in form%}
                      <div id="campo_formulario">
                      <label for="{{field.id_for_label}}">
                          {{field.label}}
                      </label><br>
                      {{field}}
                      </div>
                      {% if field.id_for_label == 'id_password' %}
                      <div id="campo_formulario">
                        <label for="id_password2">
                            Repita Password
                        </label><br>
                        <input type="password" name="password2" maxlength="20" required id="id_password2">
                      </div>
                      {% endif %}
                  {% endfor %}
                  <div id="campo_formulario">
                    <input type="submit" value="Enviar">
                    <input type="reset" value="Limpiar">
                  </div>
              </form>
            </div>
            <div class="alert alert-success" role="alert">
              {{ mensaje }}
            </div>
        </main>
    
        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                  <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                  <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                  <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>
        {% load static%}
        <script src="{% static 'core/js/validaciones.js' %}"></script>
    </body>


</html>

TestDjango/core/templates/core/form_mod_juego.html
<!DOCTYPE html>
<html>
   
    <head>
        {% load static%}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HORA RATA</title>
        <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    </head>

    <body>
        <div>
            <a id="inicio" href="/">>Inicio</a>
            <nav>
                {% if role == '2' %}
                  <p id='inicio_sesion'>Su perfil es Administrador</a>
                {% endif %}
            </nav>
        </div>
        
        <header>
            <h2>
                ADMINISTRADOR DE CATEGORÍAS
            </h2>
        </header>

        <main>
            <div class="contenido">
                <br>

                <div class="formulario">
                    <form method="post" id="formulario_registro" enctype="multipart/form-data" onreset="location.reload()">
                        {% csrf_token %}
                        {% for field in form%}
                            <div id="campo_formulario">
                                <label for="{{field.id_for_label}}">
                                    {{field.label}}
                                </label><br>
                                {% if field.id_for_label == 'id_id_juego' %}                      
                                    <input type="text" value="{{field.value}}" name="id_juego" id="id_id_categoria" readonly="readonly">
                                    <br>
                                {% else %}
                                    {{field}}
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div id="campo_formulario">
                            <input type="submit" value="Enviar">
                            <input type="reset" value="Limpiar">
                        </div>
                    </form>
                </div>
                <div class="alert alert-success" role="alert">
                    {{ mensaje }}
                </div>
            </div>
        </main>

        <footer>
            <p class="texto-footer">Juegos Rata es una tienda exclusivamente online. Encuentranos en nuestras redes sociales:</p>
            {% load static%}
            <div class="footer-block">
                <div class="image-on-top">
                    <img src="{% static 'core/img/icono_insta.png' %}" alt="Instagram">
                    <img src="{% static 'core/img/icono_tiktok.png' %}" alt="Tik Tok">
                    <img src="{% static 'core/img/icono_x.png' %}" alt="Twitter">
                </div>
            </div>
        </footer>
    </body>

</html>